name: autoapp

services:
  wh:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: autoapp
      DB_USER: autoapp
      DB_PASS: autoapp
      settings: dev
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ../src:/app/
    networks:
      - postgres-network

  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: autoapp
      POSTGRES_USER: autoapp
      POSTGRES_PASSWORD: autoapp
    ports:
      - 5432:5432
    networks:
      - postgres-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres-network

networks:
  postgres-network:
