name: "WH-auto"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: SSH Remote Commands
        run: |
          cd ${{ github.workspace }}
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to server
        run: |
          ssh root@${{ secrets.SERVER_IP }} 'bash -s' < ./setup.sh
